---
title: SDGAP Procurement
timezone: America/New_York
collections:
  notices:
    title: Notices
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: notices
  values:
    layout: default
    File: ''
    Type: RFP
    Reference-Number: 
    title: 
    Posted-Date: 
    Deadline-Date: 
date: 2016-10-02 17:11:00.000000000 Z
url: sdgap-procurement.org
permalink: "/:title.html"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
email: your-email@domain.com
baseurl: "/foo"
exclude:
- ".gitignore"
- gulpfile.js
- package.json
- browser-sync.js
- ".jekyll-metadata"
- node_modules
description: A simple, open, and transparent collection of procurements from the Sri
  Lanka Strengthening Democratic Governance and Accountability Project.
destination: "./build"
sass:
  style: compressed
